---
- hosts: web
  remote_user: guest
  become: yes
  become_method: sudo
  tasks:
   - name: Add group "{{ uvar }}" to remote server
     group:
       name: "{{ uvar }}"
       gid: "{{ idvar }}"
       state: present
   - name: Add user "{{ uvar }}"
     user:
       name: "{{ uvar }}"
       uid: "{{ idvar }}"
       comment: Oracle DB user
       shell: /bin/bash
       group: "{{ uvar }}"
       password: $6$NZW7P9twLOr1ESuU$q/wnmL7wVWLwVrehn1E0jjouF.EReQ18H7SivzxQPQtT1R.wbsCTPIzEZ8BlOoo4AVKyPIDR2IldKW0OjBFi51

